stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3-jdk-18
  stage: build
  script: "mvn package -B"

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=<hapy-time> --api-key=0387500d-93dd-46de-b150-e379c1003673
  only:
    - stg